USE [master]
GO

/****** Object:  Database [BDII]    Script Date: 07.05.2019 21:15:13 ******/
CREATE DATABASE [BDII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDII', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BDII.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDII_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BDII_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BDII] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDII].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDII] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDII] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDII] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDII] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDII] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDII] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDII] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDII] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDII] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDII] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDII] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDII] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDII] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDII] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDII] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDII] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDII] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDII] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDII] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDII] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDII] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDII] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDII] SET RECOVERY FULL 
GO

ALTER DATABASE [BDII] SET  MULTI_USER 
GO

ALTER DATABASE [BDII] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDII] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDII] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDII] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDII] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDII] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDII] SET  READ_WRITE 
GO

